name: Sync code to Gitte

on:
  push:
    branches: [ "main" ]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Synchronize code to the image repository
      uses: Yikun/hub-mirror-action@v1.2
      with:
        src: github/YingLunTown-DreamLand-Development-Group
        dst: gitee/Happy2018new
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: "DreamLand-YingLunTown"
        force_update: true
        mappings: "DreamLand-YingLunTown=>DreamLand-YingLunTown-Mirror"
